name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - platform: linux/amd64
          arch: x86_64
          image: docker.io/archlinux:base-devel
        - platform: linux/arm64
          arch: aarch64
          image: ghcr.io/fwcd/archlinuxarm-docker

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      if: matrix.platform != 'linux/amd64'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ matrix.platform }}
    - name: Build packages (${{ matrix.platform }})
      run: >
        docker run
        --rm
        --env BUILDER_UID=$(id -u)
        --env BUILDER_GID=$(id -g)
        --platform "${{ matrix.platform }}"
        --mount type=bind,src="$PWD",dst="/src/${{ github.repository }}"
        --workdir "/src/${{ github.repository }}"
        --entrypoint "/src/${{ github.repository }}/with-builder-user"
        ${{ matrix.image }}
        ./build-pkgs
    - name: Build package database
      run: >
        docker run
        --rm
        --user "$(id -u):$(id -g)"
        --mount type=bind,src="$PWD",dst="/src/${{ github.repository }}"
        --workdir "/src/${{ github.repository }}"
        archlinux
        ./build-db
