name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - platform: linux/amd64
          image: docker.io/archlinux:base-devel

    steps:
    - uses: actions/checkout@v3
    - name: Build packages (${{ matrix.platform }})
      run: >
        docker run
        --rm
        --env BUILDER_UID=$(id -u)
        --env BUILDER_GID=$(id -g)
        --platform "${{ matrix.platform }}"
        --mount type=bind,src="$PWD",dst="/src/${{ github.repository }}"
        --workdir "/src/${{ github.repository }}"
        --entrypoint "/src/${{ github.repository }}"/docker-entrypoint
        ${{ matrix.image }}
